### ISSUE TITLE
I cannot visit the page by the IE browser.

### ISSUE THREAD

**Issue by wuwanga** [jpypi/RPyServer#1]
Thanks for your sharing of this webserver project. I was learning the basic http protocol now and I want to build a tiny webserver by python. Luckly, I found your project in gihub, and I found that I cannot visit the page when I use the IE browser with your RPyServer. Could you give me some advises about this problem? Thank you very much!

**Comment by jpypi** [comment]
Happy to help! I need a little more information though to help figure this out.
What version of IE are you trying to use? Are you running the server on Windows?
Were you trying to access just a plain HTML page such as `hello.html` in the sample `www` folder or trying to just hit the server and get a default index page?

The way things are currently, I've not tested running CGI on Windows. The server assumes the script can be run with a shebang (e.g `#!/path/binary`) as on a *nix type system. This also was written in python2 so there are issues where `/usr/bin/python` is py3, but the CGI pages make use of things like print statements without parentheses.

**Comment by wuwanga** [comment]
Thanks for your reply. I ran the RPyServer on ubuntu16.04 not on Windows. But I couldn't visit the website through the IE browser (All versions) both the HTML pages and CGI pages.  The page is empty on the IE browser.

**Comment by jpypi** [comment]
It appears that the issue is compression. There are two common compression encodings: gzip and deflate. They happen to be similar, however certain browsers have messed up their implementations, specifically, IE. We can trick IE by sending `Content-Encoding: gzip`, which will still let the server send data compressed using `DEFLATE` and have things work properly. **However**, this breaks browsers which have implemented things properly (firefox, edge, safari, and likely chrome). See the answer here for a more detailed explanation:
http://stackoverflow.com/questions/388595/why-use-deflate-instead-of-gzip-for-text-files-served-by-apache

This could probably be remedied by adjusting the response `Content-Encoding` header based on the user agent string. However, IE is a rather garbage browser, in my opinion. I'd recommend just using anything except for that. ;)
Could also possibly, alternatively, use actual gzip. (I have not tried this.) Trouble is that the gzip implementation in python2, which this project was written in, is not an easy swap out as it is in python3.

You can easily run the server without compression using:
`sudo python2 http_server2.py -noc`
This will make everything work in any browser.

**Comment by wuwanga** [comment]
Thanks, I will try it again.
